package ar.edu.itba.pdc.natto.protocol.xmpp.models;

/**
 * Created by natinavas on 10/26/16.
 */
public class Stream extends Tag {

    public Stream(){
        super("stream", false);
    }


    /**
     * For initial stream headers in both client-to-server and server-to-
     server communication, the initiating entity MUST include the 'to'
     attribute and MUST set its value to a domainpart that the initiating
     entity knows or expects the receiving entity to service.
     */
    public StringBuilder getTo(){
        return getAttribute("to");
    }

    /**
     * The 'from' attribute specifies an XMPP identity of the entity sending
     the stream element.
     */
    public StringBuilder getFrom(){
        return getAttribute("from");
    }

    /**
     * The 'id' attribute specifies a unique identifier for the stream,
     called a "stream ID".  The stream ID MUST be generated by the
     receiving entity when it sends a response stream header and MUST BE
     unique within the receiving application (normally a server).
     */
    public StringBuilder getId(){
        return getAttribute("id");
    }

    /**
     * The 'xml:lang' attribute specifies an entity's preferred or default
     language for any human-readable XML character data to be sent over
     the stream (an XML stanza can also possess an 'xml:lang' attribute,
     as discussed under Section 8.1.5)
     */
    public StringBuilder getLang(){
        return getAttribute("xml:lang");
    }

    /**
     * The inclusion of the version attribute set to a value of at least
     "1.0" signals support for the stream-related protocols defined in
     this specification, including TLS negotiation (Section 5), SASL
     negotiation (Section 6), stream features (Section 4.3.2), and stream
     errors (Section 4.9).
     */
    public StringBuilder getVersion(){
        return getAttribute("version");
    }




}

